---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmChart
metadata:
  name: cozyllm-vllm-inference
  namespace: cozy-public
spec:
  chart: ./free/packages/apps/vllm-inference
  interval: 1m
  reconcileStrategy: Revision
  sourceRef:
    kind: GitRepository
    name: cozyllm
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmChart
metadata:
  name: cozyllm-litellm
  namespace: cozy-public
spec:
  chart: ./free/packages/apps/litellm
  interval: 1m
  reconcileStrategy: Revision
  sourceRef:
    kind: GitRepository
    name: cozyllm
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmChart
metadata:
  name: cozyllm-comfyui
  namespace: cozy-public
spec:
  chart: ./free/packages/apps/comfyui
  interval: 1m
  reconcileStrategy: Revision
  sourceRef:
    kind: GitRepository
    name: cozyllm
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmChart
metadata:
  name: cozyllm-jupyterhub
  namespace: cozy-public
spec:
  chart: ./free/packages/apps/jupyterhub
  interval: 1m
  reconcileStrategy: Revision
  sourceRef:
    kind: GitRepository
    name: cozyllm
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmChart
metadata:
  name: cozyllm-langflow
  namespace: cozy-public
spec:
  chart: ./free/packages/apps/langflow
  interval: 1m
  reconcileStrategy: Revision
  sourceRef:
    kind: GitRepository
    name: cozyllm
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmChart
metadata:
  name: cozyllm-comfyui-workload
  namespace: cozy-public
spec:
  chart: ./free/packages/system/comfyui-workload
  interval: 1m
  reconcileStrategy: Revision
  sourceRef:
    kind: GitRepository
    name: cozyllm
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmChart
metadata:
  name: cozyllm-lakehouse
  namespace: cozy-public
spec:
  chart: ./free/packages/apps/lakehouse
  interval: 1m
  reconcileStrategy: Revision
  sourceRef:
    kind: GitRepository
    name: cozyllm
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmChart
metadata:
  name: cozyllm-trino
  namespace: cozy-public
spec:
  chart: ./free/packages/apps/trino
  interval: 1m
  reconcileStrategy: Revision
  sourceRef:
    kind: GitRepository
    name: cozyllm
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmChart
metadata:
  name: cozyllm-sparkcluster
  namespace: cozy-public
spec:
  chart: ./free/packages/apps/sparkcluster
  interval: 1m
  reconcileStrategy: Revision
  sourceRef:
    kind: GitRepository
    name: cozyllm
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmChart
metadata:
  name: cozyllm-airflow
  namespace: cozy-public
spec:
  chart: ./free/packages/apps/airflow
  interval: 1m
  reconcileStrategy: Revision
  sourceRef:
    kind: GitRepository
    name: cozyllm
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmChart
metadata:
  name: cozyllm-mlflow
  namespace: cozy-public
spec:
  chart: ./free/packages/apps/mlflow
  interval: 1m
  reconcileStrategy: Revision
  sourceRef:
    kind: GitRepository
    name: cozyllm
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmChart
metadata:
  name: cozyllm-coder
  namespace: cozy-public
spec:
  chart: ./free/packages/apps/coder
  interval: 1m
  reconcileStrategy: Revision
  sourceRef:
    kind: GitRepository
    name: cozyllm
