---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: cozyllm-contrib
  namespace: cozy-public
spec:
  interval: 1m0s
  ref:
    branch: main
  timeout: 60s
  url: https://github.com/aenix-io/cozyllm
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cozyllm-contrib
  namespace: cozy-system
spec:
  interval: 5m
  targetNamespace: cozy-system
  chart:
    spec:
      chart: ./contrib/packages/core/platform
      sourceRef:
        kind: GitRepository
        name: cozyllm-contrib
        namespace: cozy-public
      reconcileStrategy: Revision
